#ifndef CORE_LIBS_PRX_LIBSCEAGCDRIVER_EXECUTION_INCLUDE_VULKANLIBRARY_HPP
#define CORE_LIBS_PRX_LIBSCEAGCDRIVER_EXECUTION_INCLUDE_VULKANLIBRARY_HPP

namespace AgcDriver {

const char* ResolveVulkanLibrary();

}

#endif
